### PR TITLE
Add Heroku Button support

### PR DESCRIPTION
**Pull request by ukd1**
@paxan did some great initial work on getting this working on Heroku; I've taken it a little further and added Heroku Button support (i.e. one click, setup the env vars, done) and added auto-parsing of @mongolab URI's (I used MongoLab, as it's free).

If you have any comments, I'd love to try address them.

This:
- [x] add's heroku button support, giving one click setup
- [x] fixes the screenshot which was broken

### CODE REVIEW

**Comment by ukd1** [comment]
@gdb anything you'd like me to change?

**Comment by gdb** [comment]
Nice! @antifuchs is a better person to ask now that I'm no longer at Stripe.

**Comment by antifuchs** [comment]
Yep, I like this. Thanks so much for making this!

**Comment by paxan** [comment]
:+1:

**Pull request merged**
